In [118]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt 
plt.rc("font", size=14)

from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn import metrics
from sklearn.metrics import roc_auc_score, recall_score, classification_report
from sklearn.model_selection import StratifiedKFold, cross_val_score, cross_validate
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from collections import Counter
from sklearn.metrics import roc_auc_score
from sklearn.datasets import make_classification
from imblearn.over_sampling import RandomOverSampler
from sklearn.preprocessing import StandardScaler
from pandas import DataFrame

import seaborn as sns
sns.set(style="white")
sns.set(style="whitegrid", color_codes=True)

In [119]:
df = pd.read_excel (r'/Users/MaeganBoosten/Thesis_Project/Final/Original_SHAP.xlsx')
print (df)

     duration  credit_amount  intallment_rate  residence_since       age  \
0    0.256953       1.078480         0.918477        -0.765977 -0.751642   
1   -0.240857      -0.237923         0.918477         1.046987  2.590552   
2    0.505858      -0.248556         0.024147         0.140505 -1.279356   
3    0.256953       1.168508        -0.870183        -0.765977 -1.279356   
4    2.248194       1.165673         0.024147        -0.765977 -1.015499   
..        ...            ...              ...              ...       ...   
369  1.252574       1.757239        -0.870183        -0.765977 -0.839594   
370 -0.738668      -0.877693         0.918477         1.046987  1.535122   
371 -0.738668      -0.912429         0.918477        -0.765977  0.919455   
372  0.256953      -0.728473         0.918477         1.046987  0.215835   
373 -0.738668      -0.615760        -1.764514        -1.672459 -1.103451   

     number_of_existcr  number_of_dependents  telephon   foreign  \
0             1.027

In [120]:
#Logistic regression 

In [121]:
from sklearn.model_selection import train_test_split
from sklearn import model_selection

In [122]:
X = df.drop('False Positive', axis=1)
y = df['False Positive'] 

In [123]:
print(X.shape, y.shape)

(374, 114) (374,)


In [124]:
#Oversampling

In [125]:
# summarize class distribution
print(Counter(y))
# define oversampling strategy
oversample = RandomOverSampler(sampling_strategy='minority')
# fit and apply the transform
X_over, y_over = oversample.fit_resample(X, y)
# summarize class distribution
print(Counter(y_over))

Counter({0: 270, 1: 104})
Counter({1: 270, 0: 270})


In [126]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
import statsmodels.formula.api as smf
import statsmodels.api as sm

In [90]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X_over, y_over, test_size=0.5, random_state=42)

In [127]:
sum(y_train)

136

In [128]:
len(y_train)

270

In [117]:
print(X_train.shape, X_test.shape)

(270, 114) (270, 114)


In [91]:
# instantiate model
logreg = LogisticRegression(random_state=42, solver = 'newton-cg')

In [92]:
# fit model
logreg.fit(X_train, y_train)

LogisticRegression(random_state=42, solver='newton-cg')

In [93]:
y_pred_train = logreg.predict(X_train)
y_pred_class = logreg.predict(X_test)

In [94]:
# predicting 
y_pred_class

array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0])

In [95]:
sum(y_train)

136

In [96]:
sum(y_test)

134

In [97]:
logreg.predict_proba(X_test)

array([[3.65112857e-01, 6.34887143e-01],
       [9.62762351e-01, 3.72376487e-02],
       [1.33407001e-01, 8.66592999e-01],
       [9.80240157e-02, 9.01975984e-01],
       [2.17729712e-02, 9.78227029e-01],
       [2.78702860e-01, 7.21297140e-01],
       [8.04518879e-02, 9.19548112e-01],
       [3.16480853e-01, 6.83519147e-01],
       [1.94502675e-01, 8.05497325e-01],
       [8.40772372e-02, 9.15922763e-01],
       [7.92741402e-01, 2.07258598e-01],
       [8.40210248e-01, 1.59789752e-01],
       [4.62784677e-02, 9.53721532e-01],
       [4.74197558e-01, 5.25802442e-01],
       [7.28810245e-01, 2.71189755e-01],
       [9.58703818e-01, 4.12961816e-02],
       [9.00088565e-01, 9.99114349e-02],
       [3.50946265e-01, 6.49053735e-01],
       [2.27344338e-01, 7.72655662e-01],
       [6.33980662e-01, 3.66019338e-01],
       [2.49170652e-01, 7.50829348e-01],
       [9.24368975e-01, 7.56310253e-02],
       [9.77999126e-01, 2.20008743e-02],
       [6.25491881e-01, 3.74508119e-01],
       [6.193145

In [98]:
def acc_val(TP, TN, FP, FN, data):    
    accuracy = (TP + TN) / float(TP + TN + FP + FN)
    recall = TP / float(FN + TP)
    specificity = TN / (TN + FP)
    false_positive_rate = FP / float(TN + FP)
    precision = TP / float(TP + FP)
    F1 = 2 * (precision * recall) / (precision + recall)
    print('The values for {} are:'.format(data))
    print('Accuracy: {} ,Recall: {} , Specificity: {} , False Positive Rate: {} , Precision: {}, F1 Score: {}'.format(accuracy, recall, specificity, false_positive_rate,
                                                                                                                   precision, F1))

In [99]:
# test data 
confusion = metrics.confusion_matrix(y_test, y_pred_class)
print(confusion)
TP1 = confusion[1, 1]
TN1 = confusion[0, 0]
FP1 = confusion[0, 1]
FN1 = confusion[1, 0]
acc_val(TP1, TN1, FP1, FN1, 'Test Data')

[[87 49]
 [43 91]]
The values for Test Data are:
Accuracy: 0.6592592592592592 ,Recall: 0.6791044776119403 , Specificity: 0.6397058823529411 , False Positive Rate: 0.3602941176470588 , Precision: 0.65, F1 Score: 0.6642335766423357


In [100]:
# train data 
confusion = metrics.confusion_matrix(y_train, y_pred_train)
print(confusion)
TP2 = confusion[1, 1]
TN2 = confusion[0, 0]
FP2 = confusion[0, 1]
FN2 = confusion[1, 0]
acc_val(TP2, TN2, FP2, FN2, 'Train Data')

[[106  28]
 [ 31 105]]
The values for Train Data are:
Accuracy: 0.7814814814814814 ,Recall: 0.7720588235294118 , Specificity: 0.7910447761194029 , False Positive Rate: 0.208955223880597 , Precision: 0.7894736842105263, F1 Score: 0.7806691449814126


In [101]:
roc_auc_score(y_test, logreg.predict(X_test))

0.6594051799824407

In [102]:
roc_auc_score(y_train, logreg.predict(X_train))

0.7815517998244075

In [103]:
#Parameter tuning

In [104]:
# define models and parameters
model = LogisticRegression()
solvers = ['newton-cg', 'lbfgs', 'liblinear']
penalty = ['l2']
c_values = [100, 10, 1.0, 0.1, 0.01]
# define grid search
grid = dict(solver=solvers,penalty=penalty,C=c_values)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
grid_search = GridSearchCV(estimator=model, param_grid=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_result = grid_search.fit(X_test, y_test)
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
params = grid_result.cv_results_['params']

Best: 0.650617 using {'C': 0.01, 'penalty': 'l2', 'solver': 'newton-cg'}
