In [49]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt 
plt.rc("font", size=14)

from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn import metrics
from sklearn.metrics import roc_auc_score, recall_score, classification_report
from sklearn.model_selection import StratifiedKFold, cross_val_score, cross_validate
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from collections import Counter
from sklearn.metrics import roc_auc_score
from sklearn.datasets import make_classification
from imblearn.over_sampling import RandomOverSampler
from sklearn.preprocessing import StandardScaler
from pandas import DataFrame

import seaborn as sns
sns.set(style="white")
sns.set(style="whitegrid", color_codes=True)

In [50]:
df = pd.read_excel (r'/Users/MaeganBoosten/Thesis_Project/Final/Original.xlsx')
print (df)

     duration  credit_amount  intallment_rate  residence_since       age  \
0    0.256953       1.078480         0.918477        -0.765977 -0.751642   
1   -0.240857      -0.237923         0.918477         1.046987  2.590552   
2    0.505858      -0.248556         0.024147         0.140505 -1.279356   
3    0.256953       1.168508        -0.870183        -0.765977 -1.279356   
4    2.248194       1.165673         0.024147        -0.765977 -1.015499   
..        ...            ...              ...              ...       ...   
369  1.252574       1.757239        -0.870183        -0.765977 -0.839594   
370 -0.738668      -0.877693         0.918477         1.046987  1.535122   
371 -0.738668      -0.912429         0.918477        -0.765977  0.919455   
372  0.256953      -0.728473         0.918477         1.046987  0.215835   
373 -0.738668      -0.615760        -1.764514        -1.672459 -1.103451   

     number_of_existcr  number_of_dependents  telephon   foreign  \
0             1.027

In [51]:
#Logistic regression 

In [52]:
from sklearn.model_selection import train_test_split
from sklearn import model_selection

In [53]:
X = df.drop('False Positive', axis=1)
y = df['False Positive'] 

In [54]:
print(X.shape, y.shape)

(374, 57) (374,)


In [55]:
#Oversampling

In [56]:
# summarize class distribution
print(Counter(y))
# define oversampling strategy
oversample = RandomOverSampler(sampling_strategy='minority')
# fit and apply the transform
X_over, y_over = oversample.fit_resample(X, y)
# summarize class distribution
print(Counter(y_over))

Counter({0: 270, 1: 104})
Counter({1: 270, 0: 270})


In [57]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
import statsmodels.formula.api as smf
import statsmodels.api as sm

In [58]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X_over, y_over, test_size=0.5, random_state=42)

In [59]:
# instantiate model
logreg = LogisticRegression(random_state=42, solver = 'newton-cg')

In [60]:
# fit model
logreg.fit(X_train, y_train)

LogisticRegression(random_state=42, solver='newton-cg')

In [61]:
y_pred_train = logreg.predict(X_train)
y_pred_class = logreg.predict(X_test)

In [62]:
# predicting 
y_pred_class

array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0])

In [63]:
len(y_train)

270

In [64]:
logreg.predict_proba(X_test)

array([[3.78734146e-01, 6.21265854e-01],
       [9.35272921e-01, 6.47270786e-02],
       [2.15077702e-01, 7.84922298e-01],
       [1.02415260e-01, 8.97584740e-01],
       [4.13038527e-01, 5.86961473e-01],
       [3.44992759e-01, 6.55007241e-01],
       [2.03279708e-01, 7.96720292e-01],
       [7.59670068e-02, 9.24032993e-01],
       [3.98257121e-01, 6.01742879e-01],
       [2.15077702e-01, 7.84922298e-01],
       [8.25630471e-01, 1.74369529e-01],
       [2.21314638e-01, 7.78685362e-01],
       [4.57480285e-01, 5.42519715e-01],
       [4.37820054e-01, 5.62179946e-01],
       [9.29079867e-01, 7.09201334e-02],
       [9.76574946e-01, 2.34250544e-02],
       [4.16443268e-04, 9.99583557e-01],
       [5.94216322e-01, 4.05783678e-01],
       [9.38500631e-02, 9.06149937e-01],
       [8.43526017e-01, 1.56473983e-01],
       [2.35191325e-01, 7.64808675e-01],
       [7.57896498e-01, 2.42103502e-01],
       [9.76965094e-01, 2.30349057e-02],
       [7.26010550e-01, 2.73989450e-01],
       [5.968781

In [65]:
def acc_val(TP, TN, FP, FN, data):    
    accuracy = (TP + TN) / float(TP + TN + FP + FN)
    recall = TP / float(FN + TP)
    specificity = TN / (TN + FP)
    false_positive_rate = FP / float(TN + FP)
    precision = TP / float(TP + FP)
    F1 = 2 * (precision * recall) / (precision + recall)
    print('The values for {} are:'.format(data))
    print('Accuracy: {} ,Recall: {} , Specificity: {} , False Positive Rate: {} , Precision: {}, F1 Score: {}'.format(accuracy, recall, specificity, false_positive_rate,
                                                                                                                   precision, F1))

In [66]:
# test data 
confusion = metrics.confusion_matrix(y_test, y_pred_class)
print(confusion)
TP1 = confusion[1, 1]
TN1 = confusion[0, 0]
FP1 = confusion[0, 1]
FN1 = confusion[1, 0]
acc_val(TP1, TN1, FP1, FN1, 'Test Data')

[[87 49]
 [42 92]]
The values for Test Data are:
Accuracy: 0.662962962962963 ,Recall: 0.6865671641791045 , Specificity: 0.6397058823529411 , False Positive Rate: 0.3602941176470588 , Precision: 0.6524822695035462, F1 Score: 0.6690909090909091


In [67]:
# train data 
confusion = metrics.confusion_matrix(y_train, y_pred_train)
print(confusion)
TP2 = confusion[1, 1]
TN2 = confusion[0, 0]
FP2 = confusion[0, 1]
FN2 = confusion[1, 0]
acc_val(TP2, TN2, FP2, FN2, 'Train Data')

[[109  25]
 [ 26 110]]
The values for Train Data are:
Accuracy: 0.8111111111111111 ,Recall: 0.8088235294117647 , Specificity: 0.8134328358208955 , False Positive Rate: 0.1865671641791045 , Precision: 0.8148148148148148, F1 Score: 0.8118081180811809


In [68]:
roc_auc_score(y_test, logreg.predict(X_test))

0.6631365232660228

In [69]:
#Hyperparameter tuning

In [48]:
# define models and parameters
model = LogisticRegression()
solvers = ['newton-cg', 'lbfgs', 'liblinear']
penalty = ['l2']
c_values = [100, 10, 1.0, 0.1, 0.01]
# define grid search
grid = dict(solver=solvers,penalty=penalty,C=c_values)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
grid_search = GridSearchCV(estimator=model, param_grid=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_result = grid_search.fit(X_test, y_test)
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
params = grid_result.cv_results_['params']

Best: 0.639506 using {'C': 100, 'penalty': 'l2', 'solver': 'newton-cg'}
